import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 사이드바 설정
 * 각 플랫폼(Web, Android, iOS)별로 별도의 메뉴 그룹을 만듭니다.
 */
const sidebars: SidebarsConfig = {
  // 1. Web용 사이드바: docs/web 폴더의 내용을 자동으로 가져옴
  webSidebar: [
    {
      type: 'autogenerated',
      dirName: 'web', 
    },
  ],

  // 2. Android용 사이드바: docs/android 폴더의 내용을 자동으로 가져옴
  androidSidebar: [
    {
      type: 'autogenerated',
      dirName: 'android',
    },
  ],

  // 3. iOS용 사이드바: docs/ios 폴더의 내용을 자동으로 가져옴
  iosSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ios',
    },
  ],
};

export default sidebars;