import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * 사이드바 설정
 * 각 플랫폼(Web, Android, iOS)별로 별도의 메뉴 그룹을 만듭니다.
 */
const sidebars: SidebarsConfig = {
  integrationSidebar: [
    {
      type: "doc",
      id: "integration/intro",
      label: "들어가기 앞서",
    },
    {
      type: "category",
      label: "Flutter",
      link: {
        type: "generated-index",
        description: "Flutter 플러그인에 대한 문서 목록입니다."
      },
      items: [
          "integration/flutter/getting-started",
        {
          type: "category",
          label: "광고",
          link: {
            type: "generated-index",
            description: "Adsynapse Flutter 플러그인에서 제공하는 기능 문서 목록"
          },
          items: [
            "integration/flutter/banner/how-to-use",
            "integration/flutter/native/how-to-use",
          ]
        }
      ],
    },
    // {
    //   type: "category",
    //   label: "Web",
    //   collapsible: true,
    //   collapsed: false,
    //   link: {
    //     type: "generated-index",
    //     description: "Web 플랫폼에 대한 문서 목록입니다."
    //   },
    //   items: [
    //
    //   ],
    // },
    // {
    //   type: "autogenerated",
    //   dirName: "integration"
    // }
  ],
};

export default sidebars;
