import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// 자동 생성: docs-claire/ 의 문서를 frontmatter의 sidebar_position 순으로 나열.
// CMS(/admin)에서 새 문서를 만들어도 이 파일을 고칠 필요가 없다.
const sidebars: SidebarsConfig = {
  claireSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
