openapi: 3.0.0
info:
  title: SDK API Reference
  version: 1.0.0
  description: API 명세서 테스트 파일입니다.
servers:
  - url: http://localhost:3000
paths:
  /test:
    get:
      summary: 테스트 API
      responses:
        '200':
          description: 성공
components: {}
